# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: ZWEwNDkwM2E2MjJhOTdmOGZhNDMwYTAzNjdjNjgxMDViMTk2MmQ5ZmMwNjViMTM2ZDU3MmNkNjFmNTA0NDYxNDVlMWMyZDY4YmExMDg4OTUxNTAzYmE5YWI1OTVjMjI2NzI3YTA4Y2M0NmM2MjY0ODk4MDMyMmE4MWM1YmI4YTE=
