# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  datasource:
    username: root
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: NGFmMmIxYmY5MjM5MjQ5ZjE4MDU3YWZjY2NkZDI2NDVhMWI0ZTE0NTEzNTQ4NDAyMDU1NTQxYWM4ZDEyZTA2NDcyNmQ3Y2NlMWVjZmEwOThiYmQyMDA1YzlkNDliYjk2YzRlZWQxYTU0MzNhN2JhNWI2NWI0OGYzZGZmZDM5OWQ=
