package com.taller.app.domain;

import static com.taller.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class DetalleOrdenAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleOrdenAllPropertiesEquals(DetalleOrden expected, DetalleOrden actual) {
        assertDetalleOrdenAutoGeneratedPropertiesEquals(expected, actual);
        assertDetalleOrdenAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleOrdenAllUpdatablePropertiesEquals(DetalleOrden expected, DetalleOrden actual) {
        assertDetalleOrdenUpdatableFieldsEquals(expected, actual);
        assertDetalleOrdenUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleOrdenAutoGeneratedPropertiesEquals(DetalleOrden expected, DetalleOrden actual) {
        assertThat(actual)
            .as("Verify DetalleOrden auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleOrdenUpdatableFieldsEquals(DetalleOrden expected, DetalleOrden actual) {
        assertThat(actual)
            .as("Verify DetalleOrden relevant properties")
            .satisfies(a -> assertThat(a.getDescripcion()).as("check descripcion").isEqualTo(expected.getDescripcion()))
            .satisfies(a -> assertThat(a.getCantidad()).as("check cantidad").isEqualTo(expected.getCantidad()))
            .satisfies(a ->
                assertThat(a.getPrecio()).as("check precio").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrecio())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertDetalleOrdenUpdatableRelationshipsEquals(DetalleOrden expected, DetalleOrden actual) {
        assertThat(actual)
            .as("Verify DetalleOrden relationships")
            .satisfies(a -> assertThat(a.getOrdenTrabajo()).as("check ordenTrabajo").isEqualTo(expected.getOrdenTrabajo()));
    }
}
