package com.taller.app.domain;

import static com.taller.app.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class OrdenTrabajoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenTrabajoAllPropertiesEquals(OrdenTrabajo expected, OrdenTrabajo actual) {
        assertOrdenTrabajoAutoGeneratedPropertiesEquals(expected, actual);
        assertOrdenTrabajoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenTrabajoAllUpdatablePropertiesEquals(OrdenTrabajo expected, OrdenTrabajo actual) {
        assertOrdenTrabajoUpdatableFieldsEquals(expected, actual);
        assertOrdenTrabajoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenTrabajoAutoGeneratedPropertiesEquals(OrdenTrabajo expected, OrdenTrabajo actual) {
        assertThat(actual)
            .as("Verify OrdenTrabajo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenTrabajoUpdatableFieldsEquals(OrdenTrabajo expected, OrdenTrabajo actual) {
        assertThat(actual)
            .as("Verify OrdenTrabajo relevant properties")
            .satisfies(a -> assertThat(a.getFecha()).as("check fecha").isEqualTo(expected.getFecha()))
            .satisfies(a -> assertThat(a.getEstado()).as("check estado").isEqualTo(expected.getEstado()))
            .satisfies(a -> assertThat(a.getObservaciones()).as("check observaciones").isEqualTo(expected.getObservaciones()))
            .satisfies(a -> assertThat(a.getMecanico()).as("check mecanico").isEqualTo(expected.getMecanico()))
            .satisfies(a ->
                assertThat(a.getManoObra()).as("check manoObra").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getManoObra())
            )
            .satisfies(a ->
                assertThat(a.getSubtotal()).as("check subtotal").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getSubtotal())
            )
            .satisfies(a -> assertThat(a.getTotal()).as("check total").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getTotal()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrdenTrabajoUpdatableRelationshipsEquals(OrdenTrabajo expected, OrdenTrabajo actual) {
        assertThat(actual)
            .as("Verify OrdenTrabajo relationships")
            .satisfies(a -> assertThat(a.getVehiculo()).as("check vehiculo").isEqualTo(expected.getVehiculo()));
    }
}
