package com.taller.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class VehiculoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAllPropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertVehiculoAutoGeneratedPropertiesEquals(expected, actual);
        assertVehiculoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAllUpdatablePropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertVehiculoUpdatableFieldsEquals(expected, actual);
        assertVehiculoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoAutoGeneratedPropertiesEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(actual)
            .as("Verify Vehiculo auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoUpdatableFieldsEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(actual)
            .as("Verify Vehiculo relevant properties")
            .satisfies(a -> assertThat(a.getPlaca()).as("check placa").isEqualTo(expected.getPlaca()))
            .satisfies(a -> assertThat(a.getMarca()).as("check marca").isEqualTo(expected.getMarca()))
            .satisfies(a -> assertThat(a.getModelo()).as("check modelo").isEqualTo(expected.getModelo()))
            .satisfies(a -> assertThat(a.getColor()).as("check color").isEqualTo(expected.getColor()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertVehiculoUpdatableRelationshipsEquals(Vehiculo expected, Vehiculo actual) {
        assertThat(actual)
            .as("Verify Vehiculo relationships")
            .satisfies(a -> assertThat(a.getCliente()).as("check cliente").isEqualTo(expected.getCliente()));
    }
}
